[colors]
background       = '#1f1f24'
black            = '#43454b'
blue             = '#4ec4e6'
cursor           = '#ffffff'
cyan             = '#83c9bc'
foreground       = '#ffffff'
green            = '#b1faeb'
magenta          = '#ff85b8'
red              = '#ff8a7a'
tabs             = '#838991'
tabs-active      = '#6bdfff'
white            = '#ffffff'
yellow           = '#d9c668'
dim-black        = '#43454b'
dim-blue         = '#6bdfff'
dim-cyan         = '#cda1ff'
dim-foreground   = '#e5cfff'
dim-green        = '#83c9bc'
dim-magenta      = '#ff85b8'
dim-red          = '#ff8a7a'
dim-white        = '#ffffff'
dim-yellow       = '#d9c668'
light-black      = '#6bdfff'
light-blue       = '#6bdfff'
light-cyan       = '#4ec4e6'
light-foreground = '#ffffff'
light-green      = '#b1faeb'
light-magenta    = '#ff85b8'
light-red        = '#ff8a7a'
light-white      = '#ffffff'
light-yellow     = '#d9c668'
