[colors]
background       = '#ffffff'
black            = '#8a99a6'
blue             = '#0058a1'
cursor           = '#000000'
cyan             = '#355d61'
foreground       = '#000000'
green            = '#174145'
magenta          = '#9c2191'
red              = '#ad1805'
tabs             = '#8a99a6'
tabs-active      = '#0058a1'
white            = '#ffffff'
yellow           = '#78492a'
dim-black        = '#8a99a6'
dim-blue         = '#003f73'
dim-cyan         = '#174145'
dim-foreground   = '#000000'
dim-green        = '#174145'
dim-magenta      = '#9c2191'
dim-red          = '#ad1805'
dim-white        = '#ffffff'
dim-yellow       = '#78492a'
light-black      = '#8a99a6'
light-blue       = '#0058a1'
light-cyan       = '#355d61'
light-foreground = '#000000'
light-green      = '#174145'
light-magenta    = '#9c2191'
light-red        = '#ad1805'
light-white      = '#ffffff'
light-yellow     = '#78492a'
